### ISSUE TITLE
4.0: basename_max

### ISSUE THREAD

**Issue by candrews** [ROCm-Developer-Tools/ROCclr#19]
Running `clinfo` with version 4.0, after the `clinfo` output, I get a core dump:
```  clinfo 
LoadLib(libhsa-amd-aqlprofile64.so) failed: libhsa-amd-aqlprofile64.so: cannot open shared object file: No such file or directory
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP.dbg (3212.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback 
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     gfx803
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 
  Driver Version                                  3212.0 (HSA1.1,LC)
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Board Name (AMD)                         Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
  Device PCI-e ID (AMD)                           0x67df
  Device Topology (AMD)                           PCI-E, 01:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               36
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             1380MHz
  Graphics IP (AMD)                               8.0
  Device Partition                                (core)
    Max number of sub-devices                     36
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024
clinfo: /var/tmp/portage/dev-libs/rocclr-4.0.0/work/ROCclr-rocm-4.0.0/compiler/lib/utils/options.cpp:1568: void amd::option::Options::setDumpFileName(const char*): Assertion `basename_max != -1' failed.
Aborted (core dumped)
```

Here's the line with the failed assertion: https://github.com/ROCm-Developer-Tools/ROCclr/blob/rocm-4.0.0/compiler/lib/utils/options.cpp#L1568

**Comment by candrews** [comment]
Here's the output of running in `gdb` and getting a backtrace:
```
$ gdb clinfo
GNU gdb (Gentoo 10.1 vanilla) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from clinfo...
Reading symbols from /usr/lib/debug//usr/bin/clinfo.debug...
(No debugging symbols found in /usr/lib/debug//usr/bin/clinfo.debug)
(gdb) run
Starting program: /usr/bin/clinfo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff0b5b640 (LWP 3056929)]
LoadLib(libhsa-amd-aqlprofile64.so) failed: libhsa-amd-aqlprofile64.so: cannot open shared object file: No such file or directory
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP.dbg (3212.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback 
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     gfx803
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 
  Driver Version                                  3212.0 (HSA1.1,LC)
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Board Name (AMD)                         Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
  Device PCI-e ID (AMD)                           0x67df
  Device Topology (AMD)                           PCI-E, 01:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               36
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             1380MHz
  Graphics IP (AMD)                               8.0
  Device Partition                                (core)
    Max number of sub-devices                     36
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024

Thread 1 "clinfo" received signal SIGSEGV, Segmentation fault.
0x0000000000000f21 in ?? ()
(gdb) bt
#0  0x0000000000000f21 in ?? ()
#1  0x00007ffff6ad8e68 in lld::SpecificAlloc<std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> > >::reset() () from /usr/lib/llvm/roc/lib/liblldELF.so.12roc
#2  0x00007ffff6a4b84d in lld::freeArena() () from /usr/lib/llvm/roc/lib/liblldCommon.so.12roc
#3  0x00007ffff6acd5fc in lld::elf::link(llvm::ArrayRef<char const*>, bool, llvm::raw_ostream&, llvm::raw_ostream&) () from /usr/lib/llvm/roc/lib/liblldELF.so.12roc
#4  0x00007ffff73633c8 in COMGR::linkWithLLD(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&) [clone .lto_priv.0] () from /usr/lib64/libamd_comgr.so.1
#5  0x00007ffff7367c22 in COMGR::AMDGPUCompiler::executeInProcessDriver(llvm::ArrayRef<char const*>) () from /usr/lib64/libamd_comgr.so.1
#6  0x00007ffff7371705 in dispatchCompilerAction(amd_comgr_action_kind_s, COMGR::DataAction*, COMGR::DataSet*, COMGR::DataSet*, llvm::raw_ostream&) () from /usr/lib64/libamd_comgr.so.1
#7  0x00007ffff73738eb in amd_comgr_do_action () from /usr/lib64/libamd_comgr.so.1
#8  0x00007ffff7d264de in device::Program::linkImplLC(amd::option::Options*) () from /usr/lib64/libamdocl64.so
#9  0x00007ffff7d4915b in amd::Program::build(std::vector<amd::Device*, std::allocator<amd::Device*> > const&, char const*, void (*)(_cl_program*, void*), void*, bool, bool) [clone .constprop.0] () from /usr/lib64/libamdocl64.so
#10 0x00007ffff7cd5286 in clBuildProgram () from /usr/lib64/libamdocl64.so
#11 0x00007ffff7dc84ae in clBuildProgram () from /usr/lib64/libOpenCL.so.1
#12 0x0000555555563f80 in device_info_wg ()
#13 0x0000555555564cf5 in printDeviceInfo ()
#14 0x00005555555659e8 in printPlatformDevices ()
#15 0x000055555555be15 in main ()
```

**Comment by shtrophic** [comment]
Also getting this on 5.6.1, but only when run as a nologin user

```
❯ sudo -u nologin-user -- /opt/rocm/bin/clinfo
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP.dbg (3570.0)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback


  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    AMD Radeon RX 6700 XT
  Device Topology:                               PCI[ B#45, D#0, F#0 ]
  Max compute units:                             20
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           256
  Preferred vector width char:                   4
  Preferred vector width short:                  2
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      4
  Native vector width short:                     2
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           2855Mhz
  Address bits:                                  64
  Max memory allocation:                         10937905968
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          8
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            16384
  Max image 3D height:                           16384
  Max image 3D depth:                            8192
  Max samplers within kernel:                    29663
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16384
  Global memory size:                            12868124672
  Constant buffer size:                          10937905968
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             65536
  Max pipe arguments:                            16
  Max pipe active reservations:                  16
  Max pipe packet size:                          2347971376
  Max global variable size:                      10937905968
  Max global variable preferred total size:      12868124672
  Max read/write image args:                     64
  Max on device events:                          1024
  Queue on device max size:                      8388608
  Max on device queues:                          1
  Queue on device preferred size:                262144
  SVM capabilities:
    Coarse grain buffer:                         Yes
    Fine grain buffer:                           Yes
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
clinfo: /usr/src/debug/rocm-opencl-runtime/ROCclr-rocm-5.6.1/compiler/lib/utils/options.cpp:1570: void amd::option::Options::setDumpFileName(const char*): Assertion `basename_max != -1' failed.
[1]    13538 IOT instruction  sudo -u litellm-ollama -- /opt/rocm/bin/clinfo
```

When run as my personal desktop user, this doesn't happen.
